# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queries_all', '0001_initial'),
        ('service_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_messages', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_call_log', models.BooleanField(blank=True, null=True)),
                ('is_offer', models.BooleanField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('is_portfolio', models.BooleanField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries_all.query')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service')),
            ],
        ),
    ]
