# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_orders', '0002_initial'),
        ('package_carts', '0001_initial'),
        ('package_orders', '0001_initial'),
        ('service_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('order_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_in_package', models.CharField(max_length=100)),
                ('base_price', models.FloatField()),
                ('service_name', models.CharField(max_length=255)),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='all_orders.order')),
                ('order_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_orders.orderpackage')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_carts.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service')),
            ],
        ),
    ]
