# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queries_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryVendor',
            fields=[
                ('query_vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_accepted', models.BooleanField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('has_been_replaced', models.BooleanField(blank=True, null=True)),
                ('mode_office', models.BooleanField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries_all.query')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors_all.vendor')),
            ],
        ),
    ]
