# Generated by Django 6.0.3 on 2026-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('Photographer', 'Photographer'), ('Decorator', 'Decorator'), ('Caterer', 'Caterer'), ('Venue Provider', 'Venue Provider'), ('Makeup Artist', 'Makeup Artist'), ('DJ / Musician', 'DJ / Musician'), ('Event Planner', 'Event Planner'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
