# Generated by Django 6.0.3 on 2026-04-05 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries_all', '0003_query_all_vendors_declined_query_arrival_time_and_more'),
        ('vendors_all', '0002_vendor_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryvendor',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queryvendor',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='queryvendor',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queryvendor',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queryvendor',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queryvendor',
            name='vendor_position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='max_orders_per_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='vendor',
            name='monthly_lead_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='razorpay_linked_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='response_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='score_boost_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('active', 'Active'), ('premium', 'Premium')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queryvendor',
            name='has_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queryvendor',
            name='has_been_replaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queryvendor',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='queries_all.query'),
        ),
        migrations.AlterField(
            model_name='queryvendor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('replaced', 'Replaced')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='queryvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to='vendors_all.vendor'),
        ),
        migrations.CreateModel(
            name='VendorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_solicitation_clause', models.BooleanField(default=False)),
                ('commission_rate_agreed', models.BooleanField(default=False)),
                ('dispute_policy_agreed', models.BooleanField(default=False)),
                ('platform_rules_agreed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='vendors_all.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_date', models.DateField(blank=True, null=True)),
                ('block_type', models.CharField(choices=[('manual', 'Personal Holiday'), ('recurring', 'Recurring (Weekly)'), ('auto', 'Auto-blocked (Max Orders)')], default='manual', max_length=20)),
                ('recurring_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='vendors_all.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_linked_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='vendors_all.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=500)),
                ('cloudinary_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('blurry', 'Image is blurry'), ('stock', 'Stock photo detected'), ('irrelevant', 'Not relevant to services'), ('low_res', 'Resolution too low'), ('other', 'Other')], max_length=50, null=True)),
                ('occasion_tag', models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('wedding', 'Wedding'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vendors_all.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.IntegerField()),
                ('new_score', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='vendors_all.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('share_phone', 'Shared personal phone'), ('share_insta', 'Shared Instagram/business name'), ('ask_upi', 'Asked for direct UPI'), ('direct_discount', 'Offered direct booking discount'), ('external_booking', 'Booked client outside platform'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Suspension'), ('ban', 'Permanent Ban')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='vendors_all.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('wedding', 'Wedding'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='vendors_all.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'occasion')},
            },
        ),
    ]
