# Generated by Django 6.0.3 on 2026-04-05 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors_all', '0003_queryvendor_accepted_at_queryvendor_assigned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPremiumLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('subscribed', 'Subscribed'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('halted', 'Payment Halted')], max_length=20)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_logs', to='vendors_all.vendor')),
            ],
        ),
    ]
