# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_categories_all', '0001_initial'),
        ('tags_all', '0001_initial'),
        ('vendors_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=50, null=True)),
                ('manage_stock', models.BooleanField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('menu_order', models.IntegerField(blank=True, null=True)),
                ('purchase_note', models.TextField(blank=True, null=True)),
                ('overriding_policy', models.TextField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, null=True)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='vendors_all.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_categories_all.category')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('service_tags_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags_all.tag')),
            ],
        ),
    ]
