# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_orders', '0001_initial'),
        ('package_carts', '0001_initial'),
        ('package_type_carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('order_package_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packages', to='all_orders.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_carts.package')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_type_carts.packagetype')),
            ],
        ),
    ]
