# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOrder',
            fields=[
                ('manual_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('service_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=50)),
                ('total_paid', models.FloatField()),
                ('service_details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_all.user')),
            ],
        ),
    ]
