# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumVendor',
            fields=[
                ('premium_vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('premium_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='packages_all.premiumpackage')),
            ],
        ),
    ]
