# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_locations', '0001_initial'),
        ('users_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('image_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('generated_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_desc', models.TextField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('expected_price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_all.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slot_no', models.IntegerField(blank=True, null=True)),
                ('recorded_call', models.BooleanField(default=False)),
                ('whatsapp_notification', models.BooleanField(default=False)),
                ('image_generation', models.BooleanField(default=False)),
                ('chat_bot', models.BooleanField(default=False)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_generation_all.imagecategory')),
            ],
        ),
    ]
