# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package_carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('package_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.FloatField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='package_carts.package')),
            ],
        ),
    ]
