# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('service_date', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(blank=True, null=True)),
                ('approx_budget', models.FloatField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
