# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queries_all', '0001_initial'),
        ('service_all', '0001_initial'),
        ('users_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service'),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_all.user'),
        ),
    ]
