# Generated by Django 6.0.3 on 2026-04-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries_all', '0002_initial'),
        ('service_all', '0001_initial'),
        ('users_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='all_vendors_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='budget_range_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='budget_range_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='city_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='floor_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='guest_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('wedding', 'Wedding'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_vendor_found', 'No Vendor Found')], default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='query',
            name='theme_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_all.service'),
        ),
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='users_all.user'),
        ),
    ]
