# Generated by Django 6.0.3 on 2026-04-05 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CityHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('active_leads', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('active_vendors', models.IntegerField(default=0)),
                ('gmv_today', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('user_complaint_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('REFUNDED', 'Refunded'), ('PAYOUT_HELD', 'Payout Held'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=30)),
                ('payout_held', models.BooleanField(default=False)),
                ('refund_issued', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_deadline', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sla_deadline'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_rating', models.FloatField(default=0.4)),
                ('weight_acceptance_rate', models.FloatField(default=0.3)),
                ('weight_response_time', models.FloatField(default=0.2)),
                ('weight_reviews', models.FloatField(default=0.1)),
                ('commission_tier1', models.FloatField(default=0.12)),
                ('commission_tier2', models.FloatField(default=0.1)),
                ('commission_tier3', models.FloatField(default=0.08)),
                ('acceptance_window_minutes', models.IntegerField(default=15)),
                ('auto_reassign_on_timeout', models.BooleanField(default=True)),
                ('auto_hold_on_dispute', models.BooleanField(default=True)),
                ('broadcast_wa_on_new_lead', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
