# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding_all', '0001_initial'),
        ('users_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingOrder',
            fields=[
                ('bidding_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('final_price', models.FloatField()),
                ('bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding_all.bidding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_all.user')),
            ],
        ),
    ]
