# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_locations', '0001_initial'),
        ('queries_all', '0002_initial'),
        ('service_all', '0001_initial'),
        ('vendors_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryOrder',
            fields=[
                ('query_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('final_price', models.FloatField()),
                ('service_details', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_locations.location')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries_all.query')),
                ('query_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors_all.queryvendor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service')),
            ],
        ),
    ]
