# Generated by Django 6.0.3 on 2026-04-05 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_orders', '0003_order_approx_budget_order_arrival_time_and_more'),
        ('vendors_all', '0002_vendor_vendor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('relay_number', models.CharField(max_length=20)),
                ('vendor_number', models.CharField(blank=True, max_length=20, null=True)),
                ('client_number_masked', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('call_status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer')], default='initiated', max_length=20)),
                ('exotel_call_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='all_orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='vendors_all.vendor')),
            ],
        ),
    ]
