# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_locations', '0001_initial'),
        ('vendors_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('vendor_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_locations.location')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors_all.vendor')),
            ],
        ),
    ]
