# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='paid', max_length=50)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all_orders.order')),
            ],
        ),
    ]
