# Generated by Django 6.0.3 on 2026-03-30 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_messages', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_call_log', models.BooleanField(blank=True, null=True)),
                ('is_offer', models.BooleanField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('is_portfolio', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('generated_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_desc', models.TextField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('expected_price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('image_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('total_price', models.FloatField()),
                ('total_package', models.IntegerField()),
                ('total_items', models.IntegerField()),
                ('paid_percent', models.IntegerField()),
                ('bidding_order_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('address', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('package_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPackage',
            fields=[
                ('premium_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('timeline', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('service_date', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(blank=True, null=True)),
                ('approx_budget', models.FloatField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_status', models.CharField(blank=True, max_length=50, null=True)),
                ('manage_stock', models.BooleanField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('menu_order', models.IntegerField(blank=True, null=True)),
                ('purchase_note', models.TextField(blank=True, null=True)),
                ('overriding_policy', models.TextField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, null=True)),
                ('ratings', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blacklist_status', models.CharField(default='active', max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bidding_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_price', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
                ('generated_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generatedimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slot_no', models.IntegerField(blank=True, null=True)),
                ('recorded_call', models.BooleanField(default=False)),
                ('whatsapp_notification', models.BooleanField(default=False)),
                ('image_generation', models.BooleanField(default=False)),
                ('chat_bot', models.BooleanField(default=False)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagecategory')),
            ],
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_package', models.BooleanField(default=False)),
                ('total_price', models.FloatField()),
                ('is_saved', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('package_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.FloatField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageLocation',
            fields=[
                ('package_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('order_package_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packages', to='core.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
            ],
        ),
        migrations.CreateModel(
            name='CartPackage',
            fields=[
                ('cart_package_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_packages', to='core.cart')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
            ],
        ),
        migrations.CreateModel(
            name='PackageTypeCategory',
            fields=[
                ('package_type_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagecategory')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='paid', max_length=50)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp_start', models.DateTimeField(blank=True, null=True)),
                ('time_stamp_end', models.DateTimeField(blank=True, null=True)),
                ('url_audio', models.URLField(blank=True, max_length=500, null=True)),
                ('text_log', models.TextField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.chat')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.query')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.query'),
        ),
        migrations.AddField(
            model_name='chat',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.query'),
        ),
        migrations.CreateModel(
            name='QueryVendor',
            fields=[
                ('query_vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_accepted', models.BooleanField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('has_been_replaced', models.BooleanField(blank=True, null=True)),
                ('mode_office', models.BooleanField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.query')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='QueryOrder',
            fields=[
                ('query_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('final_price', models.FloatField()),
                ('service_details', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.query')),
                ('query_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.queryvendor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.chat')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.query')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('order_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_in_package', models.CharField(max_length=100)),
                ('base_price', models.FloatField()),
                ('service_name', models.CharField(max_length=255)),
                ('total_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_services', to='core.order')),
                ('order_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderpackage')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.CreateModel(
            name='CartPackageService',
            fields=[
                ('cart_package_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('cart_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.cartpackage')),
                ('package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagecategory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('service_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('service_packages_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
                ('package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagecategory')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('service_tags_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('has_image', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.order')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.package')),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.packagetype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(max_length=50)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.user'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reported_id', models.IntegerField()),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('has_image', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumVendor',
            fields=[
                ('premium_vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('premium_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.premiumpackage')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_vendors', to='core.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
        ),
        migrations.CreateModel(
            name='ManualOrder',
            fields=[
                ('manual_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('service_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=50)),
                ('total_paid', models.FloatField()),
                ('service_details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BiddingOrder',
            fields=[
                ('bidding_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('final_price', models.FloatField()),
                ('bidding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bidding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('vendor_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_package', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistPackage',
            fields=[
                ('wishlist_package_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagetype')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_packages', to='core.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistPackageService',
            fields=[
                ('wishlist_package_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packagecategory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('wishlist_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wishlistpackage')),
            ],
        ),
    ]
