# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_all', '0001_initial'),
        ('image_generation_all', '0001_initial'),
        ('users_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bidding_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_price', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_all.address')),
                ('generated_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_generation_all.generatedimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_all.user')),
            ],
        ),
    ]
