# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('total_price', models.FloatField()),
                ('total_package', models.IntegerField()),
                ('total_items', models.IntegerField()),
                ('paid_percent', models.IntegerField()),
                ('bidding_order_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('address', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_date', models.DateTimeField()),
            ],
        ),
    ]
