# Generated by Django 6.0.3 on 2026-04-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_orders', '0002_initial'),
        ('queries_all', '0002_initial'),
        ('users_all', '0001_initial'),
        ('vendors_all', '0002_vendor_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approx_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='order',
            name='d1_needs_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='d1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispute_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='exotel_call_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='has_dispute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='occasion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('held', 'Held'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='relay_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='theme_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_payout_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bidding_order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='query', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='razorpay', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='queries_all.query'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('lead_accepted', 'Lead Accepted'), ('price_confirmed', 'Price Confirmed'), ('payment_received', 'Payment Received'), ('d1_ready', 'D-1 Ready'), ('delivered', 'Delivered'), ('paid_out', 'Paid Out'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='lead_accepted', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_package',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users_all.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendors_all.vendor'),
        ),
    ]
