# Generated by Django 6.0.3 on 2026-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_carts', '0001_initial'),
        ('all_locations', '0001_initial'),
        ('service_all', '0001_initial'),
        ('users_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users_all.user'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all_locations.location'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_all.service'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_all.user'),
        ),
    ]
